### ISSUE TITLE
Set up Node.js project

### ISSUE THREAD

**Issue by wrenliang** [ubclaunchpad/dough-bros#4]

**Comment by mebesius** [comment]
- Node.js + Express
- Simple 'Hello World' setup

**Comment by mebesius** [comment]
Did we want to add stuff like linting now or leave that for later?

**Comment by mebesius** [comment]
Do we want to remove the `/bin` folder?

**Comment by wrenliang** [comment]
Yeah linting would be great! You don't have to do it this week, but we definitely want to have tslint set up at some point.

**Comment by wrenliang** [comment]
Is that the nodemon `/bin` folder? As long as our `npm start` script generates the bin properly every time, I don't think we need to track it with git

**Comment by mebesius** [comment]
> 
> 
> Yeah linting would be great! You don't have to do it this week, but we definitely want to have tslint set up at some point.

We had this discussion already, but for everyone else on the team's record, `tslint` is deprecated now. For the time being, I have added linting options to the `tsconfig.json` file.

>
>
> Is that the nodemon /bin folder? As long as our npm start script generates the bin properly every time, I don't think we need to track it with git

I believe it was, but I have set up `nodemon` to monitor the `/build` folder now instead since that is where `tsc` will create our compiled files. After building `index.ts` after editing it while the server was running, no `/bin` folder is being created by `nodemon` so I removed it rather than adding it to our `.gitignore`
