### ISSUE TITLE
Backend: Documentation

### ISSUE THREAD

**Issue by wrenliang** [ubclaunchpad/dough-bros#81]

**Comment by wrenliang** [comment]
@mebesius You can look into Postman testing suites if you want (pro: complete end-to-end), or write some Jest unit tests (pro: Travis will be able to run checks).

**Comment by mebesius** [comment]
@wrenliang After looking into Postman testing suites, I think it is better to write out some unit tests since the free tier for Postman is quite restrictive. Under the free tier, we have 25 shared requests for a team and we already have 25 routes defined in our code and we may need to add more routes as the iOS app's UI becomes more fleshed out this term.

**Comment by wrenliang** [comment]
@mebesius Hey Odin, we talked about this in the meeting. Think we're gonna stick to using the Postman Collection Isabelle shared for end-to-end testing. So yeah I agree, let's just work on writing some Jest unit tests
